{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "warpstream-agent.fullname" . }}-clusterrolebinding
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "warpstream-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "warpstream-agent.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
