apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warpstream-agent.fullname" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
data:
  WARPSTREAM_BUCKET_URL: {{ .Values.config.bucketURL | quote }}
  WARPSTREAM_DEFAULT_VIRTUAL_CLUSTER_ID: {{ .Values.config.virtualClusterID | quote }}
  WARPSTREAM_REGION: {{ .Values.config.region | quote }}
