{{- if .Values.config.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpstream-agent.secretName" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
data:
  apikey: {{  required "A valid config.apiKey is required" .Values.config.apiKey |  b64enc }}
type: Opaque
{{- end }}
