apiVersion: v1
kind: Service
metadata:
  name: {{ include "warpstream-agent.fullname" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "warpstream-agent.selectorLabels" . | nindent 4 }}
